### Nordpool cheapest sequential 3 hours
- platform: template
  sensors:
    cheapest_hours_energy_tomorrow:
      device_class: timestamp
      friendly_name: "Cheapest sequential electricity hours"
      value_template: >
        {%- set numberOfSequentialHours = 3 -%}
        {%- set data = state_attr('sensor.tomorrow_lowest_price_2', 'data') -%}
        {%- if data and data|length >= numberOfSequentialHours -%}
          {%- set ns = namespace(cheapestPrice=99999, cheapestHour=None) -%}
          {%- for i in range(numberOfSequentialHours, data|length + 1) -%}
            {%- set total = 0 -%}
            {%- for j in range(i - numberOfSequentialHours, i) -%}
              {%- set total = total + data[j].price -%}
            {%- endfor -%}
            {%- if total < ns.cheapestPrice -%}
              {%- set ns.cheapestPrice = total -%}
              {%- set ns.cheapestHour = data[i - numberOfSequentialHours].start -%}
            {%- endif -%}
          {%- endfor -%}
          {{ ns.cheapestHour }}
        {%- else -%}
          unavailable
        {%- endif -%}

### Electricity prices in SEK instead of öre.
- platform: template
  sensors:
    total_el_price:
      friendly_name: "Total Electicity buying Price"
      unit_of_measurement: "kr/kWh"
      value_template: >
        {% set Elpris = states('sensor.nord_pool_se3_current_price') | float %}
        {% set Elöverföring = 0.132 %}
        {% set Energiskatt = 0.535 %}
        {% set inkMoms = (Elpris * 1.25) + Elöverföring + Energiskatt %}
        {{ inkMoms | round(2) }}
    total_el_sell_price:
      friendly_name: "Total Electicity selling Price"
      unit_of_measurement: "kr/kWh"
      value_template: >
        {% set tekniska_verken_buy_price = 0.042 %}
        {% set tax_rate = 0.25 %}
        {% set tax_above_value = 0.60 %}
        {% set spot_price = (states('sensor.nord_pool_se3_current_price') | float) %}
        {% if spot_price > tax_above_value %}
          {% set taxable_value = spot_price - tax_above_value %}
          {% set tax = taxable_value * tax_rate %}
          {% set spot_price = spot_price - tax %}
        {% endif %}
        {{ (spot_price + tekniska_verken_buy_price) | round(2) }}
