- id: backups_went_stale
  alias: Backup went stale
  triggers:
  - trigger: state
    entity_id: binary_sensor.backups_stale
    from: 'off'
    to: 'on'
  condition: []
  actions:
  - action: notify.mobile_app_anders_s21fe
    data:
      title: Backups are Stale
      message: Please visit the 'Home Assistant Google Drive Backup ' add-on status
        page for details.
- id: '1704797823456'
  alias: Anders Is home
  description: Notify Anders when Anders is home
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.anders
      zone_entity: zone.home
      notify_device: f326594e961a48756bccbda5b2185cd2
- id: frigate_motion_detected
  alias: Notify of events
  triggers:
  - trigger: mqtt
    topic: frigate/events
  conditions:
  - condition: state
    entity_id: person.anders
    state: away
  actions:
  - action: notify.mobile_app_anders_s21fe
    data_template:
      message: Notify - A {{trigger.payload_json["after"]["label"]}} was detected
        at {{ trigger.payload_json["after"]["camera"] }} .
      data:
        image: http://ccab4aaf-frigate-fa:5000/events/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?format=android
        tag: '{{trigger.payload_json["after"]["id"]}}'
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'
        attachment:
          url: /api/frigate/notifications/{{id}}/snapshot.jpg
- id: '1705350809026'
  alias: Anylist Add Item
  description: Lägg till {item} [till] inköpslista
  use_blueprint:
    path: kevdliu/anylist_add_item.yaml
    input:
      sentence: Lägg till {item} till [min] shoppinglista
      postscript:
      - service: notify.mobile_app_anders_s21fe
        metadata: {}
        data:
          title: Anylist
          message: '{{ trigger.slots.item }}'
- id: '1705351353616'
  alias: Anylist Add Item EN
  description: Anylist Add Item EN
  use_blueprint:
    path: kevdliu/anylist_add_item.yaml
    input:
      sentence: add {item} to [my] shopping list
      postscript:
      - service: notify.mobile_app_anders_s21fe
        metadata: {}
        data:
          message: Added {{ trigger.slots.item }}
          title: Anylist add
- id: '1718178028987'
  alias: Trådfri dimmer automation
  description: Styr belysning nedervåning från trådfri dimmer
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      integration: ZHA
      helper_last_controller_event: input_text.tradfri_dimmer_last_event
      action_button_left_short: []
      action_button_center_short:
      - metadata: {}
        data: {}
        target:
          floor_id: nedervaning
        action: switch.toggle
      - metadata: {}
        data: {}
        target:
          floor_id: nedervaning
        action: light.toggle
      controller_device: fe60358f1c852f68702ff1aa55f0b0f7
- id: '1718202810350'
  alias: Knapp Olles rum
  description: Belysniong Olles rum
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      controller_device: a44a1e7f9cc0825f0833bbc13164503e
      action_button_up_short:
      - metadata: {}
        data: {}
        target:
          area_id: olles_rum
        action: light.turn_on
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          device_id: 6f205474276711900175565cd22e16f5
      action_button_up_long: []
      action_button_down_short:
      - metadata: {}
        data: {}
        target:
          area_id: olles_rum
        action: light.turn_off
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          device_id: 6f205474276711900175565cd22e16f5
      helper_last_controller_event: input_text.knapp_olles_rum_hjalpare
- id: '1719410217121'
  alias: High water usage warning
  description: ''
  triggers:
  - entity_id: sensor.water_usage
    above: 0.25
    for:
      hours: 0
      minutes: 30
      seconds: 0
    trigger: numeric_state
  conditions:
  - condition: template
    value_template: '{% set val = states(''sensor.water_usage'') %} {{ val not in
      [''unknown'', ''unavailable'', ''none''] }}

      '
  - condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.sensor.water_usage.last_changed))
      > 1800 }}

      '
  actions:
  - data:
      message: Huset har använt mer än 250 L vatten under 30 minuter!
    action: notify.notify
  mode: single
  initial_state: true
- id: '1732616159104'
  alias: Musfälla källare rörelse
  description: ''
  triggers:
  - type: vibration
    device_id: de511fc6e097efef74e49b184046601c
    entity_id: f14f0e0ade576144d115e11c124c4a5f
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: notify.mobile_app_anders_s21fe
    metadata: {}
    data:
      message: Musfälla källare detekterade rörelse
  mode: single
- id: '1732616297430'
  alias: Musfälla vinden rörelse
  description: ''
  triggers:
  - type: vibration
    device_id: 742d091b2e1d624ef09d03e74623d6b6
    entity_id: 6efc4412636b4ad9b589dc22548b6c55
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: notify.mobile_app_anders_s21fe
    metadata: {}
    data:
      message: Musfälla vinden rörelse detekterad
  mode: single
- id: '1733299378579'
  alias: Check battery levels
  description: 'Automation that notifies if battery levels are low or unavailable '
  use_blueprint:
    path: Blackshome/low-battery-notifications-and-actions.yaml
    input:
      include_button: enable_button_trigger
      include_time: time_enabled
      time: '17:00:00'
      battery_level: 10
      exclude_sensors:
        entity_id:
        - sensor.tradfri_on_off_switch_battery_plus
        - sensor.roborock_s6_maxv_batteri
        - sensor.tradfri_on_off_switch_2_battery_plus
        - sensor.frida_iphone1_battery_plus
        - sensor.knapp_ikea_battery_plus
        - sensor.tradfri_dimmer_battery_plus
        - binary_sensor.tradfri_on_off_switch_battery_low
        - binary_sensor.tradfri_on_off_switch_2_battery_low
        - binary_sensor.frida_iphone1_battery_plus_low
        - sensor.sm_g970f_battery_level
        device_id:
        - 7d14e7d4bcd8ee6b80815bb2f9e58b05
        - e755edf4ef456fad1297aa1ecc1c0952
      include_easy_notify: enable_easy_notify
      include_persistent_notification: enable_persistent_notification
      sensor_selection: enable_all_and_custom_group_sensors
      notify_device:
      - f326594e961a48756bccbda5b2185cd2
      button_entity: input_button.check_battery_levels
      global_conditions: []
- id: '1734902601715'
  alias: Energivarning
  description: Huset importerar mycket energi
  triggers:
  - entity_id:
    - sensor.p1_meter_effekt
    above: 6000
    trigger: numeric_state
    for:
      hours: 0
      minutes: 2
      seconds: 0
  conditions:
  - condition: time
    after: 06:00:00
    before: '22:00:00'
  actions:
  - data:
      title: Hög energianvändning
      message: Huset förbrukar mer än 6 kw
    action: notify.mobile_app_anders_s21fe
  mode: single
- id: '1734903609516'
  alias: Alarm - Rpi3 notify
  description: Frigate Notifications (0.12.0.2)
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.rpi3_2
      notify_device: f326594e961a48756bccbda5b2185cd2
      alert_once: true
      attachment: thumbnail
      debug: false
      message: '{{ label }} detected - {{ camera_name }}'
      title: '{{camera_name}}'
      color: steelblue
      channel: Frigate
      update_thumbnail: true
      labels: []
      icon: mdi:cctv
      state_entity: lock.ytterdorr
      state_filter_states:
      - locked
      presence_filter: person.anders
      state_filter: true
- id: '1734963178527'
  alias: 'Asuspc server övervakning '
  description: Bevaka server är online
  triggers:
  - type: not_connected
    device_id: 41cc571454292446a326630a8437b280
    entity_id: 0151c944ca7f8a98384c411b01eb93a1
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: notify.mobile_app_anders_s21fe
    metadata: {}
    data:
      message: 'Asus pc är offline '
  mode: single
- id: '1735132152780'
  alias: RPI3 server monitor
  description: Bevaka server är online
  triggers:
  - type: not_connected
    device_id: e61e9f40dff6dd6377e0a1dc3531c18b
    entity_id: 021fe229ce1e080187be311623247f2c
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 5
      seconds: 0
  conditions: []
  actions:
  - action: notify.mobile_app_anders_s21fe
    metadata: {}
    data:
      message: 'Rpi3 offline '
  mode: single
- id: '1735378350081'
  alias: Bajsknappen automation
  description: Starta boost på badrumsfläkt
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      controller_device: 4dd612cc4136d35a3619d60e7c7d2aaa
      helper_last_controller_event: input_text.bajsknappen_hjalpare
      action_button_up_short:
      - action: number.set_value
        metadata: {}
        data:
          value: '900'
        target:
          entity_id: number.pax_levante_50_boostmode_time
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.pax_levante_50_boostmode
      action_button_down_short:
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.pax_levante_50_boostmode
      action_button_up_long: []
      action_button_up_double:
      - action: number.set_value
        metadata: {}
        data:
          value: '900'
        target:
          entity_id: number.pax_levante_50_boostmode_time
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.pax_levante_50_boostmode
      button_up_double_press: true
      action_button_up_release:
      - action: number.set_value
        metadata: {}
        data:
          value: '900'
        target:
          entity_id: number.pax_levante_50_boostmode_time
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.pax_levante_50_boostmode
      button_up_long_max_loop_repeats: 1
      button_up_long_loop: true
- id: notify_ev_charge_needed
  alias: Notify EV Charging Needed
  description: Notify if conditions are met for charging the car
  triggers:
  - trigger: state
    entity_id:
    - sensor.skoda_superb_combi_charging_state
    - sensor.skoda_superb_combi_battery_percentage
    - sensor.haos_sbfspot_sma_ac_power
    - sensor.energy_production_today_remaining_2
  condition:
  - condition: state
    entity_id: device_tracker.skoda_superb_combi_position
    state: home
  - condition: numeric_state
    entity_id: sensor.skoda_superb_combi_battery_percentage
    below: 90
  - condition: state
    entity_id: sensor.skoda_superb_combi_charging_state
    state: ready_for_charging
  - condition: numeric_state
    entity_id: sensor.haos_sbfspot_sma_ac_power
    above: 4000
  - condition: template
    value_template: '{% set battery_level = states(''sensor.skoda_superb_combi_battery_percentage'')
      | float %} {% set remaining_energy_needed = 12000 if battery_level == 0 else
      battery_level / 100 * 12000 %} {{ remaining_energy_needed <= states(''sensor.energy_production_today_remaining_2'')
      | float }}

      '
  - condition: state
    entity_id: input_boolean.ev_charger_request_sent
    state: 'off'
  actions:
  - action: notify.mobile_app_anders_s21fe
    data:
      title: Dags att ladda bilen?
      message: Solproduktionen är hög och bilen har mindre än 80% batteri. Vill du
        börja ladda?
      data:
        actions:
        - action: START_CHARGE
          title: Ja, börja ladda!
        - action: NO_CHARGE
          title: Nej, inte nu
  - action: input_boolean.turn_on
    entity_id: input_boolean.ev_charger_request_sent
- id: handle_ev_charge_response
  alias: Handle EV Charge Notification Response
  triggers:
  - trigger: event
    event_type: mobile_app_notification_action
    event_data:
      action: START_CHARGE
  - trigger: event
    event_type: mobile_app_notification_action
    event_data:
      action: NO_CHARGE
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.action == ''START_CHARGE'' }}'
      sequence:
      - action: switch.turn_on
        entity_id: switch.skoda_superb_combi_charging
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.action == ''NO_CHARGE'' }}'
      sequence:
      - action: input_boolean.turn_on
        entity_id: input_boolean.ev_charger_request_sent
- id: reset_ev_notification_daily
  alias: Reset EV Notification Daily
  triggers:
  - trigger: time
    at: 00:00:01
  - trigger: state
    entity_id: sensor.skoda_superb_combi_charging_state
    from: Charging
    to: Ready for Charging
  action:
  - action: input_boolean.turn_off
    entity_id: input_boolean.ev_charger_request_sent
- id: reminder_ev_charger_not_connected
  alias: 'Påminnelse: Anslut bilens laddare'
  description: Annonsering i högtalarna när bilen är hemma, laddaren ej inkopplad,
    frontdörren har öppnats och någon är hemma.
  triggers:
  - trigger: state
    entity_id:
    - device_tracker.skoda_superb_combi_position
    from:
    to: home
  conditions:
  - condition: state
    entity_id: lock.ytterdorr
    state: unlocked
  - condition: or
    conditions:
    - condition: state
      entity_id: person.frida
      state: home
    - condition: state
      entity_id: person.anders
      state: home
  - condition: state
    entity_id: sensor.skoda_superb_combi_charging_state
    state: connect_cable
  actions:
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: tts.google_say
    target:
      entity_id: media_player.kok
    data:
      entity_id: media_player.kok
      message: Vänligen anslut laddaren till bilen.
      cache: false
      language: sv
  mode: single
- id: '1744038579159'
  alias: Automatisk belysning
  description: Tänder alla enheter märkta med 'Automatisk belysning' 2 timmar före
    solnedgång och släcker dem efter 22:00 om TV:n är avstängd, annars väntar tills
    TV:n stängs av.
  triggers:
  - event: sunset
    offset: -02:00:00
    id: 'on'
    trigger: sun
  - at: '22:00:00'
    id: 'off'
    trigger: time
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: 'on'
      sequence:
      - action: homeassistant.turn_on
        target:
          label_id: automatisk_belysning
        data: {}
    - conditions:
      - condition: trigger
        id: 'off'
      - condition: template
        value_template: '{{ states(''remote.the_frame'') != ''off'' }}'
      sequence:
      - wait_for_trigger:
        - entity_id: remote.the_frame
          to: 'off'
          trigger: state
        timeout: 02:20:00
        continue_on_timeout: true
      - action: homeassistant.turn_off
        target:
          label_id: automatisk_belysning
        data: {}
      - device_id: 439ab72d0a12b6536ad5cc48d71d60c5
        domain: climate
        entity_id: f1260d8d12a0d5939b238360a06f42d4
        type: set_hvac_mode
        hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: 'off'
      - condition: state
        entity_id: remote.the_frame
        state: 'off'
      sequence:
      - action: homeassistant.turn_off
        target:
          label_id: automatisk_belysning
        data: {}
      - device_id: 439ab72d0a12b6536ad5cc48d71d60c5
        domain: climate
        entity_id: f1260d8d12a0d5939b238360a06f42d4
        type: set_hvac_mode
        hvac_mode: 'off'
  mode: single
