# Yaml mode not enabled. Changes are persissted in .storage/lovelace

##########################
### Lovelace yaml file
# @link https://www.home-assistant.io/lovelace/
# Lovelace not configured correctly. WTF, how to configure?
# Try to find more info on hass.io
lovelace:
  resources:
    - url: /hacsfiles/custom-header/custom-header.js
      type: module

    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module

    - url: /hacsfiles/apexcharts-card.js
      type: module

    - type: module
      url: /local/apexcharts-card.js

    - url: /local/vacuum-card.js
      type: module

views:
  - title: Home
    icon: "mdi:home"
