sensor:
  - name: "Utomhustemperatur"
    unique_id: "utomhustemperatur_loggad"
    unit_of_measurement: "°C"
    state: >
      {{ state_attr('weather.forecast_hem', 'temperature') | float(0) }}
  - name: "Utomhus luftfuktighet"
    unique_id: "utomhus_humidity"
    unit_of_measurement: "%"
    state_class: measurement
    device_class: humidity
    state: >
      {{ state_attr('weather.forecast_hem', 'humidity') | float(0) }}
