sensor:
  - name: "emhass_power_load_no_var_loads"
    unique_id: "emhass_power_load_no_var_loads"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >
      {% set sensors = [
        'sensor.garage_power',
        'sensor.zeke_current_power',
        'sensor.uttag_diskmaskinen_power',
        'sensor.ikea_of_sweden_inspelning_smart_plug_power',
        'sensor.uttag_tvattmaskin_power'
      ] %}
      {% set total = states('sensor.p1_meter_effekt') | float(0) %}
      {% set sum_var = sensors | map('states') | map('float', 0) | sum %}
      {% set fixed_load = total - sum_var %}
      {{ [fixed_load, 0] | max }}