##########################################
### The new tamplate syntax
sensor:
  - name: "Asus PC server status"
    icon: mdi:server
    state: >
      {% if is_state('binary_sensor.asuspc_icmp', 'on') %}
        Online
      {% else %}
        Offline
      {% endif %}
