##########################################
### The new tamplate syntax
sensor:
  - name: "Nordpool with taxes and fees"
    unit_of_measurement: "öre/kWh"
    state: >
      {% set Elpris = states('sensor.nord_pool_se3_current_price') | float %}
      {% set Elöverföring = 13.20 %}
      {% set Energiskatt = 53.50 %}
      {% set inkMoms = (Elpris * 1.25) + Elöverföring + Energiskatt %}
      {{ inkMoms | round(2) }}
    attributes:
      unit: "kr/kWh"
      currency: "SEK"
      price_in_cents: "true"
      device_class: monetary
      icon: mdi:flash
      raw_today: >
        {% set raw_today = state_attr('sensor.se3_today_lowest_price', 'data') %}
        {% if raw_today %}
          {% set ns = namespace(adjusted_entries=[]) %}
          {% for entry in raw_today %}
            {% set Elpris = entry['price'] * 100 | float(0) %}
            {% set Elöverföring = 13.20 %}
            {% set Energiskatt = 53.50 %}
            {% set inkMoms = (Elpris * 1.25) + Elöverföring + Energiskatt %}
            {% set adjusted_entry = {
              "start": entry['start'],
              "end": entry['end'],
              "value": (inkMoms | round(2)),
              "spot": (Elpris | round(2)),
              "eon": 0.06,
              "tax": ((inkMoms - (Elpris + Elöverföring)) | round(2)),
              "transfer": (Elöverföring | round(2))
            } %}
            {% set ns.adjusted_entries = ns.adjusted_entries + [adjusted_entry] %}
          {% endfor %}
          {{ ns.adjusted_entries }}
        {% else %}
          []
        {% endif %}
      raw_tomorrow: >
        {% set raw_tomorrow = state_attr('sensor.tomorrow_lowest_price_2', 'data') %}
        {% if raw_tomorrow %}
          {% set ns = namespace(adjusted_entries=[]) %}
          {% for entry in raw_tomorrow %}
            {% set Elpris = entry['price'] * 100| float(0) %}
            {% set Elöverföring = 13.20 %}
            {% set Energiskatt = 53.50 %}
            {% set inkMoms = (Elpris * 1.25) + Elöverföring + Energiskatt %}
            {% set adjusted_entry = {
              "start": entry['start'],
              "end": entry['end'],
              "value": (inkMoms | round(2)),
              "spot": (Elpris | round(2)),
              "eon": 0.06,
              "tax": ((inkMoms - (Elpris + Elöverföring)) | round(2)),
              "transfer": (Elöverföring | round(2))
            } %}
            {% set ns.adjusted_entries = ns.adjusted_entries + [adjusted_entry] %}
          {% endfor %}
          {{ ns.adjusted_entries }}
        {% else %}
          []
        {% endif %}
  
  - name: Cheapest sequential electricity hours
    device_class: timestamp
    default_entity_id: sensor.cheapest_hours_energy_tomorrow
    state: "{%- set numberOfSequentialHours = 3 -%} {%- set data = state_attr('sensor.tomorrow_lowest_price_2',
      'data') -%} {%- if data and data|length >= numberOfSequentialHours -%}\n  {%-
      set ns = namespace(cheapestPrice=99999, cheapestHour=None) -%}\n  {%- for i
      in range(numberOfSequentialHours, data|length + 1) -%}\n    {%- set total =
      0 -%}\n    {%- for j in range(i - numberOfSequentialHours, i) -%}\n      {%-
      set total = total + data[j].price -%}\n    {%- endfor -%}\n    {%- if total
      < ns.cheapestPrice -%}\n      {%- set ns.cheapestPrice = total -%}\n      {%-
      set ns.cheapestHour = data[i - numberOfSequentialHours].start -%}\n    {%- endif
      -%}\n  {%- endfor -%}\n  {{ ns.cheapestHour }}\n{% else %}\n  {{ none }}\n{%-
      endif -%}"
  
  - name: Total Electicity buying Price
    unit_of_measurement: kr/kWh
    default_entity_id: sensor.total_el_price
    state: '{% set Elpris = states(''sensor.nord_pool_se3_current_price'') | float
      %} {% set Elöverföring = 0.132 %} {% set Energiskatt = 0.535 %} {% set inkMoms
      = (Elpris * 1.25) + Elöverföring + Energiskatt %} {{ inkMoms | round(2) }}'

  - name: Total Electicity selling Price
    unit_of_measurement: kr/kWh
    default_entity_id: sensor.total_el_sell_price
    state: "{% set tekniska_verken_buy_price = 0.042 %} {% set tax_rate = 0.25 %}
      {% set tax_above_value = 0.60 %} {% set spot_price = (states('sensor.nord_pool_se3_current_price')
      | float) %} {% if spot_price > tax_above_value %}\n  {% set taxable_value =
      spot_price - tax_above_value %}\n  {% set tax = taxable_value * tax_rate %}\n
      \ {% set spot_price = spot_price - tax %}\n{% endif %} {{ (spot_price + tekniska_verken_buy_price)
      | round(2) }}"