trigger:
  - trigger: time_pattern
    minutes: /30
  - trigger: homeassistant
    event: start
action:
  - condition: template
    value_template: "{{ now().hour >= 13 }}"
  - action: nordpool.get_prices_for_date
    data:
      config_entry: 01JM7G5FXSGG6XW02GY6WD27KR
      date: "{{ now().date() + timedelta(days=1) }}"
      areas: SE3
      currency: SEK
    response_variable: tomorrow_price
sensor:
  - name: Tomorrow lowest price
    unique_id: anders_se3_tomorrow_low_price
    availability: >
      {{ tomorrow_price is defined
         and tomorrow_price is not none
         and 'SE3' in tomorrow_price
         and tomorrow_price['SE3'] }}
    state: >
      {%- set has_price = (
          tomorrow_price is defined
          and tomorrow_price is not none
          and 'SE3' in tomorrow_price
          and tomorrow_price['SE3']
        )
      -%}
      {%- if not has_price -%}
        unavailable
      {%- else -%}
        {%- set data = namespace(prices=[]) -%}
        {%- for state in tomorrow_price['SE3'] -%}
          {%- set data.prices = data.prices + [(state.price / 1000)] -%}
        {%- endfor -%}
        {{ data.prices | min }}
      {%- endif -%}
    attributes:
      data: >
        {%- set has_price = (
            tomorrow_price is defined
            and tomorrow_price is not none
            and 'SE3' in tomorrow_price
            and tomorrow_price['SE3']
          )
        -%}
        {%- if not has_price -%}
          []
        {%- else -%}
          {%- set data = namespace(prices=[]) -%}
          {%- for state in tomorrow_price['SE3'] -%}
            {%- set data.prices = data.prices + [{
              'start': state.start,
              'end': state.end,
              'price': (state.price / 1000)
            }] -%}
          {%- endfor -%}
          {{ data.prices }}
        {%- endif -%}

