##########################################
### The new tamplate syntax
sensor:
  - name: "Water usage in liters"
    unit_of_measurement: "L"
    device_class: water
    state_class: total_increasing
    availability: >
      {{ states('sensor.water_usage') not in ['unknown', 'unavailable', 'none'] }}
    state: >
      {{ (states('sensor.water_usage') | float) * 1000 }}
