request_update:
  name: "Request value update"
  description: "Triggers an update of data associated with a specific device."
  fields:
    device_id:
      description: "The device for which to update values."
      selector:
        device:
          integration: pax_ble