##########################################
### The new tamplate syntax
sensor:
  - name: "RPI3 server status"
    icon: mdi:server
    state: >
      {% if is_state('binary_sensor.rpi3_icmp', 'on') %}
        Online
      {% else %}
        Offline
      {% endif %}
