#################################################################
## State machines för tvättmaskin, torktumlare och diskmaskin
#################################################################
input_select:
  washer_state:
    name: Tvättmaskin State
    options: [Idle, Running, Finished, Emptied]

  dryer_state:
    name: Torktumlare State
    options: [Idle, Running, Finished, Emptied]

  dishwasher_state:
    name: Diskmaskin State
    options: [Idle, Running, Finished, Emptied]

#################################################################
## Tvättmaskin
#################################################################

automation:
  - id: washer_started
    alias: Washer started
    trigger:
      - platform: numeric_state
        entity_id: sensor.uttag_tvattmaskin_power
        above: 100
        for: "00:01:00"
    condition: []
    action:
      - service: input_select.select_option
        target: { entity_id: input_select.washer_state }
        data: { option: "Running" }
    mode: single

  - id: washer_finished_or_emptied
    alias: Washer finished or emptied
    trigger:
      - platform: numeric_state
        entity_id: sensor.uttag_tvattmaskin_power
        below: 3
        for: "00:00:20"
    condition:
      - condition: state
        entity_id: input_select.washer_state
        state: "Running"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.magnetkontakt_tvattmaskin_contact
                state: "on"
            sequence:
              - service: input_select.select_option
                target: { entity_id: input_select.washer_state }
                data: { option: "Emptied" }
          - conditions: []
            sequence:
              - service: input_select.select_option
                target: { entity_id: input_select.washer_state }
                data: { option: "Finished" }
    mode: single

  - id: washer_emptied
    alias: Washer emptied
    trigger:
      - platform: state
        entity_id: binary_sensor.magnetkontakt_tvattmaskin_contact
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.washer_state
        state: "Finished"
    action:
      - service: input_select.select_option
        target: { entity_id: input_select.washer_state }
        data: { option: "Emptied" }
    mode: single

  - id: washer_back_to_idle
    alias: Washer back to Idle
    trigger:
      - platform: state
        entity_id: binary_sensor.magnetkontakt_tvattmaskin_contact
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_select.washer_state
        state: "Emptied"
    action:
      - service: input_select.select_option
        target: { entity_id: input_select.washer_state }
        data: { option: "Idle" }
    mode: single

#################################################################
## Torktumlare
#################################################################

  - id: dryer_started
    alias: Dryer started
    trigger:
      - platform: numeric_state
        entity_id: sensor.ikea_of_sweden_inspelning_smart_plug_power
        above: 100
        for: "00:01:00"
    condition: []
    action:
      - service: input_select.select_option
        target: { entity_id: input_select.dryer_state }
        data: { option: "Running" }
    mode: single

  - id: dryer_finished_or_emptied
    alias: Dryer finished or emptied
    trigger:
      - platform: numeric_state
        entity_id: sensor.ikea_of_sweden_inspelning_smart_plug_power
        below: 8
        for: "00:00:20"
    condition:
      - condition: state
        entity_id: input_select.dryer_state
        state: "Running"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.magnetkontakt_torktumlare_contact
                state: "on"
            sequence:
              - service: input_select.select_option
                target: { entity_id: input_select.dryer_state }
                data: { option: "Emptied" }
          - conditions: []
            sequence:
              - service: input_select.select_option
                target: { entity_id: input_select.dryer_state }
                data: { option: "Finished" }
    mode: single

  - id: dryer_emptied
    alias: Dryer emptied
    trigger:
      - platform: state
        entity_id: binary_sensor.magnetkontakt_torktumlare_contact
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.dryer_state
        state: "Finished"
    action:
      - service: input_select.select_option
        target: { entity_id: input_select.dryer_state }
        data: { option: "Emptied" }
    mode: single

  - id: dryer_back_to_idle
    alias: Dryer back to Idle
    trigger:
      - platform: state
        entity_id: binary_sensor.magnetkontakt_torktumlare_contact
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_select.dryer_state
        state: "Emptied"
    action:
      - service: input_select.select_option
        target: { entity_id: input_select.dryer_state }
        data: { option: "Idle" }
    mode: single

#################################################################
## Diskmaskin
#################################################################

  - id: dishwasher_started
    alias: Dishwasher started
    trigger:
      - platform: numeric_state
        entity_id: sensor.uttag_diskmaskinen_power
        above: 100
        for: "00:01:00"
    condition: []
    action:
      - service: input_select.select_option
        target: { entity_id: input_select.dishwasher_state }
        data: { option: "Running" }
    mode: single

  - id: dishwasher_finished_or_emptied
    alias: Dishwasher finished or emptied
    trigger:
      - platform: numeric_state
        entity_id: sensor.uttag_diskmaskinen_power
        below: 3
        for: "00:00:15"
    condition:
      - condition: state
        entity_id: input_select.dishwasher_state
        state: "Running"
    action:
      - service: input_select.select_option
        target: { entity_id: input_select.dishwasher_state }
        data: { option: "Finished" }
    mode: single

  - id: dishwasher_back_to_idle
    alias: Dishwasher back to Idle
    trigger:
      - platform: numeric_state
        entity_id: sensor.uttag_diskmaskinen_power
        below: 3
        for: "00:05:00"
    action:
      - service: input_select.select_option
        target: { entity_id: input_select.dishwasher_state }
        data: { option: "Idle" }
    mode: single
